"""empty message

Revision ID: 10ea94800da
Revises: 144ba57ea38
Create Date: 2016-11-29 18:26:17.458023

"""

# revision identifiers, used by Alembic.
revision = '10ea94800da'
down_revision = '144ba57ea38'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
