"""empty message

Revision ID: 113c93fa338
Revises: 245b91556e7
Create Date: 2016-11-24 19:21:39.035036

"""

# revision identifiers, used by Alembic.
revision = '113c93fa338'
down_revision = '245b91556e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
