"""empty message

Revision ID: 144ba57ea38
Revises: 1d090c6223d
Create Date: 2016-11-29 18:22:56.745202

"""

# revision identifiers, used by Alembic.
revision = '144ba57ea38'
down_revision = '1d090c6223d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
