"""empty message

Revision ID: 1553b86d853
Revises: 266e24f9833
Create Date: 2016-01-27 20:21:56.242349

"""

# revision identifiers, used by Alembic.
revision = '1553b86d853'
down_revision = '266e24f9833'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_pk_n', sa.Integer(), nullable=False),
    sa.Column('home_team_pk', sa.Integer(), nullable=True),
    sa.Column('away_team_pk', sa.Integer(), nullable=True),
    sa.Column('user_pk', sa.Integer(), nullable=True),
    sa.Column('season_n', sa.Integer(), nullable=True),
    sa.Column('day_n', sa.Integer(), nullable=True),
    sa.Column('is_played', sa.Boolean(), nullable=True),
    sa.Column('home_sets_n', sa.Integer(), nullable=True),
    sa.Column('away_sets_n', sa.Integer(), nullable=True),
    sa.Column('home_games_n', sa.Integer(), nullable=True),
    sa.Column('away_games_n', sa.Integer(), nullable=True),
    sa.Column('home_pts_n', sa.Integer(), nullable=True),
    sa.Column('away_pts_n', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_pk'], ['clubs.club_id_n'], ),
    sa.ForeignKeyConstraint(['home_team_pk'], ['clubs.club_id_n'], ),
    sa.ForeignKeyConstraint(['user_pk'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('match_pk_n')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    ### end Alembic commands ###
