"""empty message

Revision ID: 178108f8281
Revises: 46c1bbc44c2
Create Date: 2016-11-25 06:51:23.875659

"""

# revision identifiers, used by Alembic.
revision = '178108f8281'
down_revision = '46c1bbc44c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
