"""empty message

Revision ID: 1ae57379dd0
Revises: 1bf747c71b8
Create Date: 2016-11-18 21:25:09.663512

"""

# revision identifiers, used by Alembic.
revision = '1ae57379dd0'
down_revision = '1bf747c71b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
