"""empty message

Revision ID: 1b9a8592782
Revises: 27e46648844
Create Date: 2016-11-26 06:54:55.702376

"""

# revision identifiers, used by Alembic.
revision = '1b9a8592782'
down_revision = '27e46648844'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
