"""empty message

Revision ID: 1bf747c71b8
Revises: 373c29397ed
Create Date: 2016-11-18 21:17:41.322195

"""

# revision identifiers, used by Alembic.
revision = '1bf747c71b8'
down_revision = '373c29397ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
