"""empty message

Revision ID: 1ca60ca1203
Revises: 6b9423ea83
Create Date: 2017-02-13 16:31:42.687557

"""

# revision identifiers, used by Alembic.
revision = '1ca60ca1203'
down_revision = '6b9423ea83'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
