"""empty message

Revision ID: 1f131588a45
Revises: 10ea94800da
Create Date: 2017-02-10 12:51:53.498883

"""

# revision identifiers, used by Alembic.
revision = '1f131588a45'
down_revision = '10ea94800da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('current_stamina_n', sa.Integer(), default=100))
    op.add_column('players', sa.Column('endurance_n', sa.Integer(), default=10))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'endurance_n')
    op.drop_column('players', 'current_stamina_n')
    ### end Alembic commands ###
