"""empty message

Revision ID: 1f78b504f8a
Revises: 43215d7963c
Create Date: 2016-11-27 22:17:34.820949

"""

# revision identifiers, used by Alembic.
revision = '1f78b504f8a'
down_revision = '43215d7963c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
