"""empty message

Revision ID: 1fb1a2dd9b9
Revises: 22ddf6a6d19
Create Date: 2016-11-24 19:16:41.112367

"""

# revision identifiers, used by Alembic.
revision = '1fb1a2dd9b9'
down_revision = '22ddf6a6d19'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('age_n', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'age_n')
    ### end Alembic commands ###
