"""empty message

Revision ID: 209f5e97fa5
Revises: 46c61b58bf
Create Date: 2017-02-12 00:58:38.007812

"""

# revision identifiers, used by Alembic.
revision = '209f5e97fa5'
down_revision = '46c61b58bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
