"""empty message

Revision ID: 2203a6de4a4
Revises: 1f131588a45
Create Date: 2017-02-10 13:02:19.224629

"""

# revision identifiers, used by Alembic.
revision = '2203a6de4a4'
down_revision = '1f131588a45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
