"""empty message

Revision ID: 22ddf6a6d19
Revises: 4e333a27a31
Create Date: 2016-11-23 05:19:06.526257

"""

# revision identifiers, used by Alembic.
revision = '22ddf6a6d19'
down_revision = '4e333a27a31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
