"""empty message

Revision ID: 245b91556e7
Revises: 1fb1a2dd9b9
Create Date: 2016-11-24 19:19:04.902235

"""

# revision identifiers, used by Alembic.
revision = '245b91556e7'
down_revision = '1fb1a2dd9b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('is_active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'is_active')
    ### end Alembic commands ###
