"""empty message

Revision ID: 26299df67e
Revises: 178108f8281
Create Date: 2016-11-26 06:53:11.883751

"""

# revision identifiers, used by Alembic.
revision = '26299df67e'
down_revision = '178108f8281'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
