"""empty message

Revision ID: 266e24f9833
Revises: None
Create Date: 2016-01-20 21:14:54.872979

"""

# revision identifiers, used by Alembic.
revision = '266e24f9833'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('club_id_n', sa.Integer(), nullable=False),
    sa.Column('club_name_c', sa.String(length=64), nullable=True),
    sa.Column('division_n', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('club_id_n')
    )
    op.create_table('roles',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('users',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('role_pk', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.Column('managed_club_pk', sa.Integer(), nullable=True),
    sa.Column('current_season_n', sa.Integer(), nullable=True),
    sa.Column('current_day_n', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['managed_club_pk'], ['clubs.club_id_n'], ),
    sa.ForeignKeyConstraint(['role_pk'], ['roles.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('posts',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_pk'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('clubs')
    ### end Alembic commands ###
