"""empty message

Revision ID: 27e46648844
Revises: 26299df67e
Create Date: 2016-11-26 06:53:17.070315

"""

# revision identifiers, used by Alembic.
revision = '27e46648844'
down_revision = '26299df67e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
