"""empty message

Revision ID: 2a339df959f
Revises: 39fdee10748
Create Date: 2017-02-12 00:32:09.817863

"""

# revision identifiers, used by Alembic.
revision = '2a339df959f'
down_revision = '39fdee10748'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
