"""empty message

Revision ID: 2a64801f6e6
Revises: 539b5186f48
Create Date: 2017-03-12 01:56:19.592090

"""

# revision identifiers, used by Alembic.
revision = '2a64801f6e6'
down_revision = '539b5186f48'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_records',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('club_pk', sa.Integer(), nullable=True),
    sa.Column('user_pk', sa.Integer(), nullable=True),
    sa.Column('season_n', sa.Integer(), nullable=True),
    sa.Column('regular_season_position_n', sa.Integer(), nullable=True),
    sa.Column('regular_season_points_n', sa.Integer(), nullable=True),
    sa.Column('last_playoff_series_pk', sa.Integer(), nullable=True),
    sa.Column('timestamp_dt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_pk'], ['clubs.club_id_n'], ),
    sa.ForeignKeyConstraint(['last_playoff_series_pk'], ['playoff_series.pk'], ),
    sa.ForeignKeyConstraint(['user_pk'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_club_records_club_pk'), 'club_records', ['club_pk'], unique=False)
    op.create_index(op.f('ix_club_records_pk'), 'club_records', ['pk'], unique=False)
    op.create_index(op.f('ix_club_records_season_n'), 'club_records', ['season_n'], unique=False)
    op.create_index(op.f('ix_club_records_user_pk'), 'club_records', ['user_pk'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_club_records_user_pk'), table_name='club_records')
    op.drop_index(op.f('ix_club_records_season_n'), table_name='club_records')
    op.drop_index(op.f('ix_club_records_pk'), table_name='club_records')
    op.drop_index(op.f('ix_club_records_club_pk'), table_name='club_records')
    op.drop_table('club_records')
    ### end Alembic commands ###
