"""empty message

Revision ID: 2fa7fe19d34
Revises: 3badd9d6ef7
Create Date: 2016-11-22 16:55:13.824001

"""

# revision identifiers, used by Alembic.
revision = '2fa7fe19d34'
down_revision = '3badd9d6ef7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
