"""empty message

Revision ID: 32be92727a8
Revises: 2203a6de4a4
Create Date: 2017-02-11 14:00:02.108003

"""

# revision identifiers, used by Alembic.
revision = '32be92727a8'
down_revision = '2203a6de4a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('is_drafted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'is_drafted')
    ### end Alembic commands ###
