"""empty message

Revision ID: 373c29397ed
Revises: 1553b86d853
Create Date: 2016-01-27 20:22:27.054268

"""

# revision identifiers, used by Alembic.
revision = '373c29397ed'
down_revision = '1553b86d853'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
