"""empty message

Revision ID: 39fdee10748
Revises: 32be92727a8
Create Date: 2017-02-11 23:32:59.923974

"""

# revision identifiers, used by Alembic.
revision = '39fdee10748'
down_revision = '32be92727a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
