"""universities

Revision ID: 3b262636fbb
Revises: 3fdcf432d75
Create Date: 2017-04-22 01:51:30.799845

"""

# revision identifiers, used by Alembic.
revision = '3b262636fbb'
down_revision = '3fdcf432d75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name_c', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_universities_name_c'), 'universities', ['name_c'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_universities_name_c'), table_name='universities')
    op.drop_table('universities')
    ### end Alembic commands ###
