"""empty message

Revision ID: 3badd9d6ef7
Revises: None
Create Date: 2016-11-22 16:54:55.793135

"""

# revision identifiers, used by Alembic.
revision = '3badd9d6ef7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('club_id_n', sa.Integer(), nullable=False),
    sa.Column('club_name_c', sa.String(length=64), nullable=True),
    sa.Column('division_n', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('club_id_n')
    )
    op.create_table('roles',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('users',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('role_pk', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.Column('managed_club_pk', sa.Integer(), nullable=True),
    sa.Column('current_season_n', sa.Integer(), nullable=True),
    sa.Column('current_day_n', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['managed_club_pk'], ['clubs.club_id_n'], ),
    sa.ForeignKeyConstraint(['role_pk'], ['roles.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('players',
    sa.Column('pk_n', sa.Integer(), nullable=False),
    sa.Column('first_name_c', sa.String(length=64), nullable=False),
    sa.Column('second_name_c', sa.String(length=64), nullable=True),
    sa.Column('last_name_c', sa.String(length=64), nullable=False),
    sa.Column('skill_n', sa.Integer(), nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=True),
    sa.Column('club_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_pk'], ['clubs.club_id_n'], ),
    sa.ForeignKeyConstraint(['user_pk'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('pk_n')
    )
    op.create_table('posts',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_pk'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    op.create_table('matches',
    sa.Column('match_pk_n', sa.Integer(), nullable=False),
    sa.Column('home_team_pk', sa.Integer(), nullable=True),
    sa.Column('away_team_pk', sa.Integer(), nullable=True),
    sa.Column('user_pk', sa.Integer(), nullable=True),
    sa.Column('home_player_pk', sa.Integer(), nullable=True),
    sa.Column('away_player_pk', sa.Integer(), nullable=True),
    sa.Column('season_n', sa.Integer(), nullable=True),
    sa.Column('day_n', sa.Integer(), nullable=True),
    sa.Column('is_played', sa.Boolean(), nullable=True),
    sa.Column('home_sets_n', sa.Integer(), nullable=True),
    sa.Column('away_sets_n', sa.Integer(), nullable=True),
    sa.Column('home_games_n', sa.Integer(), nullable=True),
    sa.Column('away_games_n', sa.Integer(), nullable=True),
    sa.Column('home_pts_n', sa.Integer(), nullable=True),
    sa.Column('away_pts_n', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_player_pk'], ['players.pk_n'], ),
    sa.ForeignKeyConstraint(['away_team_pk'], ['clubs.club_id_n'], ),
    sa.ForeignKeyConstraint(['home_player_pk'], ['players.pk_n'], ),
    sa.ForeignKeyConstraint(['home_team_pk'], ['clubs.club_id_n'], ),
    sa.ForeignKeyConstraint(['user_pk'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('match_pk_n')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('players')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('clubs')
    ### end Alembic commands ###
