"""empty message

Revision ID: 3e568dd574f
Revises: c51d8e739c
Create Date: 2016-11-25 06:46:48.839744

"""

# revision identifiers, used by Alembic.
revision = '3e568dd574f'
down_revision = 'c51d8e739c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
