"""Messages

Revision ID: 3fdcf432d75
Revises: 3d2ead055f0
Create Date: 2017-03-25 00:35:18.062696

"""

# revision identifiers, used by Alembic.
revision = '3fdcf432d75'
down_revision = '3d2ead055f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('from_pk', sa.Integer(), nullable=True),
    sa.Column('to_pk', sa.Integer(), nullable=True),
    sa.Column('subject_c', sa.String(length=64), nullable=True),
    sa.Column('text_txt', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('timestamp_dt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_pk'], ['users.pk'], ),
    sa.ForeignKeyConstraint(['to_pk'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    ### end Alembic commands ###
