"""empty message

Revision ID: 43215d7963c
Revises: 85331b238c
Create Date: 2016-11-27 21:56:15.390262

"""

# revision identifiers, used by Alembic.
revision = '43215d7963c'
down_revision = '85331b238c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
