"""empty message

Revision ID: 46c1bbc44c2
Revises: 3e568dd574f
Create Date: 2016-11-25 06:46:55.449749

"""

# revision identifiers, used by Alembic.
revision = '46c1bbc44c2'
down_revision = '3e568dd574f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
