"""empty message

Revision ID: 46c61b58bf
Revises: 2a339df959f
Create Date: 2017-02-12 00:36:36.685187

"""

# revision identifiers, used by Alembic.
revision = '46c61b58bf'
down_revision = '2a339df959f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
