"""empty message

Revision ID: 4a495607fe2
Revises: cd3d745f6
Create Date: 2016-11-27 16:02:55.400305

"""

# revision identifiers, used by Alembic.
revision = '4a495607fe2'
down_revision = 'cd3d745f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
