"""empty message

Revision ID: 4bc89d55fd9
Revises: dcc0e2839b
Create Date: 2017-02-13 20:15:23.441700

"""

# revision identifiers, used by Alembic.
revision = '4bc89d55fd9'
down_revision = 'dcc0e2839b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("players") as batch_op:
        batch_op.add_column(sa.Column('technique_n', sa.Numeric(precision=5, scale=2), nullable=False, server_default="5.0"))
        batch_op.drop_column('technicque_n')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("players") as batch_op:
        op.add_column(sa.Column('technicque_n', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'5.0'"), autoincrement=False, nullable=False))
        op.drop_column('technique_n')
    ### end Alembic commands ###
