"""empty message

Revision ID: 4d92a799d28
Revises: 1f78b504f8a
Create Date: 2016-11-29 03:52:46.024978

"""

# revision identifiers, used by Alembic.
revision = '4d92a799d28'
down_revision = '1f78b504f8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
