"""faculties

Revision ID: 4e31c91077f
Revises: 3b262636fbb
Create Date: 2017-04-22 04:11:54.005890

"""

# revision identifiers, used by Alembic.
revision = '4e31c91077f'
down_revision = '3b262636fbb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculties',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name_c', sa.String(length=64), nullable=False),
    sa.Column('university_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['university_pk'], ['universities.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_faculties_name_c'), 'faculties', ['name_c'], unique=False)
    op.create_table('faculty_registrations',
    sa.Column('user_pk', sa.Integer(), nullable=True),
    sa.Column('faculty_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_pk'], ['faculties.pk'], ),
    sa.ForeignKeyConstraint(['user_pk'], ['users.pk'], )
    )
    op.create_table('university_registrations',
    sa.Column('user_pk', sa.Integer(), nullable=True),
    sa.Column('university_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['university_pk'], ['universities.pk'], ),
    sa.ForeignKeyConstraint(['user_pk'], ['users.pk'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('university_registrations')
    op.drop_table('faculty_registrations')
    op.drop_index(op.f('ix_faculties_name_c'), table_name='faculties')
    op.drop_table('faculties')
    ### end Alembic commands ###
