"""empty message

Revision ID: 4e333a27a31
Revises: 2fa7fe19d34
Create Date: 2016-11-23 05:07:56.182910

"""

# revision identifiers, used by Alembic.
revision = '4e333a27a31'
down_revision = '2fa7fe19d34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('full_score_c', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'full_score_c')
    ### end Alembic commands ###
