"""Initial migrations

Revision ID: 539b5186f48
Revises: None
Create Date: 2017-02-19 23:44:51.545767

"""

# revision identifiers, used by Alembic.
revision = '539b5186f48'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('club_id_n', sa.Integer(), nullable=False),
    sa.Column('club_name_c', sa.String(length=64), nullable=True),
    sa.Column('division_n', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('club_id_n')
    )
    op.create_table('roles',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('users',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('role_pk', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.Column('managed_club_pk', sa.Integer(), nullable=True),
    sa.Column('current_season_n', sa.Integer(), nullable=True),
    sa.Column('current_day_n', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['managed_club_pk'], ['clubs.club_id_n'], ),
    sa.ForeignKeyConstraint(['role_pk'], ['roles.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('financial_accounts',
    sa.Column('pk_n', sa.Integer(), nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=True),
    sa.Column('club_pk', sa.Integer(), nullable=True),
    sa.Column('money_nn', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['club_pk'], ['clubs.club_id_n'], ),
    sa.ForeignKeyConstraint(['user_pk'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('pk_n')
    )
    op.create_table('players',
    sa.Column('pk_n', sa.Integer(), nullable=False),
    sa.Column('first_name_c', sa.String(length=64), nullable=False),
    sa.Column('second_name_c', sa.String(length=64), nullable=True),
    sa.Column('last_name_c', sa.String(length=64), nullable=False),
    sa.Column('technique_n', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('endurance_n', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('current_stamina_n', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('age_n', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_drafted', sa.Boolean(), nullable=True),
    sa.Column('user_pk', sa.Integer(), nullable=True),
    sa.Column('club_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_pk'], ['clubs.club_id_n'], ),
    sa.ForeignKeyConstraint(['user_pk'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('pk_n')
    )
    op.create_table('playoff_series',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('top_seed_pk', sa.Integer(), nullable=True),
    sa.Column('low_seed_pk', sa.Integer(), nullable=True),
    sa.Column('user_pk', sa.Integer(), nullable=True),
    sa.Column('top_seed_victories_n', sa.Integer(), nullable=False),
    sa.Column('low_seed_victories_n', sa.Integer(), nullable=False),
    sa.Column('season_n', sa.Integer(), nullable=False),
    sa.Column('round_n', sa.Integer(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['low_seed_pk'], ['clubs.club_id_n'], ),
    sa.ForeignKeyConstraint(['top_seed_pk'], ['clubs.club_id_n'], ),
    sa.ForeignKeyConstraint(['user_pk'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_playoff_series_low_seed_pk'), 'playoff_series', ['low_seed_pk'], unique=False)
    op.create_index(op.f('ix_playoff_series_pk'), 'playoff_series', ['pk'], unique=False)
    op.create_index(op.f('ix_playoff_series_round_n'), 'playoff_series', ['round_n'], unique=False)
    op.create_index(op.f('ix_playoff_series_season_n'), 'playoff_series', ['season_n'], unique=False)
    op.create_index(op.f('ix_playoff_series_top_seed_pk'), 'playoff_series', ['top_seed_pk'], unique=False)
    op.create_index(op.f('ix_playoff_series_user_pk'), 'playoff_series', ['user_pk'], unique=False)
    op.create_table('posts',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_pk'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    op.create_table('matches',
    sa.Column('match_pk_n', sa.Integer(), nullable=False),
    sa.Column('home_team_pk', sa.Integer(), nullable=True),
    sa.Column('away_team_pk', sa.Integer(), nullable=True),
    sa.Column('user_pk', sa.Integer(), nullable=True),
    sa.Column('home_player_pk', sa.Integer(), nullable=True),
    sa.Column('away_player_pk', sa.Integer(), nullable=True),
    sa.Column('season_n', sa.Integer(), nullable=True),
    sa.Column('day_n', sa.Integer(), nullable=True),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.Column('status_en', sa.Enum('planned', 'finished', 'aborted'), nullable=False),
    sa.Column('playoff_series_pk', sa.Integer(), nullable=True),
    sa.Column('home_sets_n', sa.Integer(), nullable=True),
    sa.Column('away_sets_n', sa.Integer(), nullable=True),
    sa.Column('home_games_n', sa.Integer(), nullable=True),
    sa.Column('away_games_n', sa.Integer(), nullable=True),
    sa.Column('full_score_c', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['away_player_pk'], ['players.pk_n'], ),
    sa.ForeignKeyConstraint(['away_team_pk'], ['clubs.club_id_n'], ),
    sa.ForeignKeyConstraint(['home_player_pk'], ['players.pk_n'], ),
    sa.ForeignKeyConstraint(['home_team_pk'], ['clubs.club_id_n'], ),
    sa.ForeignKeyConstraint(['playoff_series_pk'], ['playoff_series.pk'], ),
    sa.ForeignKeyConstraint(['user_pk'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('match_pk_n')
    )
    op.create_index(op.f('ix_matches_away_player_pk'), 'matches', ['away_player_pk'], unique=False)
    op.create_index(op.f('ix_matches_away_team_pk'), 'matches', ['away_team_pk'], unique=False)
    op.create_index(op.f('ix_matches_day_n'), 'matches', ['day_n'], unique=False)
    op.create_index(op.f('ix_matches_home_player_pk'), 'matches', ['home_player_pk'], unique=False)
    op.create_index(op.f('ix_matches_home_team_pk'), 'matches', ['home_team_pk'], unique=False)
    op.create_index(op.f('ix_matches_match_pk_n'), 'matches', ['match_pk_n'], unique=False)
    op.create_index(op.f('ix_matches_season_n'), 'matches', ['season_n'], unique=False)
    op.create_index(op.f('ix_matches_status_en'), 'matches', ['status_en'], unique=False)
    op.create_index(op.f('ix_matches_user_pk'), 'matches', ['user_pk'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_user_pk'), table_name='matches')
    op.drop_index(op.f('ix_matches_status_en'), table_name='matches')
    op.drop_index(op.f('ix_matches_season_n'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_pk_n'), table_name='matches')
    op.drop_index(op.f('ix_matches_home_team_pk'), table_name='matches')
    op.drop_index(op.f('ix_matches_home_player_pk'), table_name='matches')
    op.drop_index(op.f('ix_matches_day_n'), table_name='matches')
    op.drop_index(op.f('ix_matches_away_team_pk'), table_name='matches')
    op.drop_index(op.f('ix_matches_away_player_pk'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_playoff_series_user_pk'), table_name='playoff_series')
    op.drop_index(op.f('ix_playoff_series_top_seed_pk'), table_name='playoff_series')
    op.drop_index(op.f('ix_playoff_series_season_n'), table_name='playoff_series')
    op.drop_index(op.f('ix_playoff_series_round_n'), table_name='playoff_series')
    op.drop_index(op.f('ix_playoff_series_pk'), table_name='playoff_series')
    op.drop_index(op.f('ix_playoff_series_low_seed_pk'), table_name='playoff_series')
    op.drop_table('playoff_series')
    op.drop_table('players')
    op.drop_table('financial_accounts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('clubs')
    ### end Alembic commands ###
