"""empty message

Revision ID: 6b9423ea83
Revises: 209f5e97fa5
Create Date: 2017-02-12 01:12:17.877396

"""

# revision identifiers, used by Alembic.
revision = '6b9423ea83'
down_revision = '209f5e97fa5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
