"""empty message

Revision ID: 7ebf8cd6ae
Revises: 4a495607fe2
Create Date: 2016-11-27 16:21:27.719563

"""

# revision identifiers, used by Alembic.
revision = '7ebf8cd6ae'
down_revision = '4a495607fe2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
