"""empty message

Revision ID: 85331b238c
Revises: dd453aedd
Create Date: 2016-11-27 17:33:36.438584

"""

# revision identifiers, used by Alembic.
revision = '85331b238c'
down_revision = 'dd453aedd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
