"""empty message

Revision ID: c51d8e739c
Revises: 113c93fa338
Create Date: 2016-11-24 19:43:22.616523

"""

# revision identifiers, used by Alembic.
revision = 'c51d8e739c'
down_revision = '113c93fa338'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
