"""empty message

Revision ID: dcc0e2839b
Revises: 1ca60ca1203
Create Date: 2017-02-13 19:36:04.532313

"""

# revision identifiers, used by Alembic.
revision = 'dcc0e2839b'
down_revision = '1ca60ca1203'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("players") as batch_op:
        batch_op.add_column(sa.Column('technicque_n', sa.Numeric(precision=5, scale=2), nullable=False, server_default="5.0"))
        batch_op.drop_column('skill_n')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('skill_n', sa.INTEGER(), nullable=False))
    op.drop_column('players', 'technicque_n')
    ### end Alembic commands ###
