"""empty message

Revision ID: dd453aedd
Revises: 7ebf8cd6ae
Create Date: 2016-11-27 16:32:40.564091

"""

# revision identifiers, used by Alembic.
revision = 'dd453aedd'
down_revision = '7ebf8cd6ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
